STATUS_NEW = 'NEW'
STATUS_CONFIRMED = 'CONFIRMED'
STATUS_CANCELLED = 'CANCELLED'
STATUS_NO_SHOW = 'NO_SHOW'
STATUS_COMPLETED = 'COMPLETED'

RESERVATION_STATUSES = [
    (STATUS_NEW, 'Новая'),
    (STATUS_CONFIRMED, 'Подтверждена'),
    (STATUS_CANCELLED, 'Отменена'),
    (STATUS_NO_SHOW, 'Не пришли'),
    (STATUS_COMPLETED, 'Завершена'),
]

OCCUPYING_STATUSES = {STATUS_NEW, STATUS_CONFIRMED}
