# Generated by Django 6.0.2 on 2026-02-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('location_note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('seats', models.PositiveIntegerField(verbose_name='Мест')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена'), ('NO_SHOW', 'Не пришли'), ('COMPLETED', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('public_code', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Код билета')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено на email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.table')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'indexes': [models.Index(fields=['date', 'start_time'], name='booking_res_date_7fc701_idx'), models.Index(fields=['table', 'date'], name='booking_res_table_i_75b0a4_idx')],
            },
        ),
    ]
