# Generated by Django 6.0.2 on 2026-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Название сайта')),
                ('site_description', models.TextField(verbose_name='Описание сайта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Логотип')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, upload_to='og/', verbose_name='OG image')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Валюта')),
                ('slot_duration_choices', models.JSONField(blank=True, default=list, verbose_name='Длительности слотов (мин.)')),
                ('min_notice_minutes', models.PositiveIntegerField(default=30, verbose_name='Минимальное время предупреждения (мин.)')),
                ('tg_enabled', models.BooleanField(default=False, verbose_name='Telegram включен')),
                ('tg_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram bot token')),
                ('tg_chat_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram chat id')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email отправителя')),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыто')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Особый день',
                'verbose_name_plural': 'Особые дни',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Понедельник ... 6=Воскресенье', unique=True, verbose_name='День недели')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыто')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Открытие')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Закрытие')),
            ],
            options={
                'verbose_name': 'График по неделе',
                'verbose_name_plural': 'График по неделе',
                'ordering': ['day_of_week'],
            },
        ),
    ]
